name: Rust

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  Rust-Tests:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: thavalon-server
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
